In [10]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/search/term"

querystring = {"q":"paris","limit":"10"}

headers = {
    'x-rapidapi-host': "aerodatabox.p.rapidapi.com",
    'x-rapidapi-key': "9613ca6ca5msh62659872159916fp1a0a2cjsndd9a3e6ff324"
    }

response = requests.get(url, headers=headers, params=querystring)

result = response.json()
result

{'searchBy': 'paris',
 'count': 6,
 'items': [{'icao': 'LFPG',
   'iata': 'CDG',
   'name': 'Paris Charles de Gaulle',
   'shortName': 'Charles de Gaulle',
   'municipalityName': 'Paris',
   'location': {'lat': 49.0128, 'lon': 2.549999},
   'countryCode': 'FR'},
  {'icao': 'LFPO',
   'iata': 'ORY',
   'name': 'Paris -Orly',
   'shortName': '-Orly',
   'municipalityName': 'Paris',
   'location': {'lat': 48.7253, 'lon': 2.35944},
   'countryCode': 'FR'},
  {'icao': 'LFAT',
   'iata': 'LTQ',
   'name': "Le Touquet-Paris-Plage Le Touquet-Côte d'Opale",
   'shortName': "Le Touquet-Côte d'Opale",
   'municipalityName': 'Le Touquet-Paris-Plage',
   'location': {'lat': 50.5174, 'lon': 1.620589},
   'countryCode': 'FR'},
  {'icao': 'LFOB',
   'iata': 'BVA',
   'name': 'Beauvais/Tillé Paris Beauvais Tillé',
   'shortName': 'Paris Beauvais Tillé',
   'municipalityName': 'Beauvais/Tillé',
   'location': {'lat': 49.4544, 'lon': 2.11278},
   'countryCode': 'FR'},
  {'icao': 'LFPB',
   'iata': 'LBG',
   'name': 'Paris -Le Bourget',
   'shortName': '-Le Bourget',
   'municipalityName': 'Paris',
   'location': {'lat': 48.9694, 'lon': 2.44139},
   'countryCode': 'FR'},
  {'icao': 'KPHT',
   'iata': 'PHT',
   'name': 'Paris Henry County',
   'shortName': 'Henry County',
   'municipalityName': 'Paris',
   'location': {'lat': 36.3382, 'lon': -88.3829},
   'countryCode': 'US'}]}

In [11]:
import pandas as pd


result['items']

[{'icao': 'LFPG',
  'iata': 'CDG',
  'name': 'Paris Charles de Gaulle',
  'shortName': 'Charles de Gaulle',
  'municipalityName': 'Paris',
  'location': {'lat': 49.0128, 'lon': 2.549999},
  'countryCode': 'FR'},
 {'icao': 'LFPO',
  'iata': 'ORY',
  'name': 'Paris -Orly',
  'shortName': '-Orly',
  'municipalityName': 'Paris',
  'location': {'lat': 48.7253, 'lon': 2.35944},
  'countryCode': 'FR'},
 {'icao': 'LFAT',
  'iata': 'LTQ',
  'name': "Le Touquet-Paris-Plage Le Touquet-Côte d'Opale",
  'shortName': "Le Touquet-Côte d'Opale",
  'municipalityName': 'Le Touquet-Paris-Plage',
  'location': {'lat': 50.5174, 'lon': 1.620589},
  'countryCode': 'FR'},
 {'icao': 'LFOB',
  'iata': 'BVA',
  'name': 'Beauvais/Tillé Paris Beauvais Tillé',
  'shortName': 'Paris Beauvais Tillé',
  'municipalityName': 'Beauvais/Tillé',
  'location': {'lat': 49.4544, 'lon': 2.11278},
  'countryCode': 'FR'},
 {'icao': 'LFPB',
  'iata': 'LBG',
  'name': 'Paris -Le Bourget',
  'shortName': '-Le Bourget',
  'municipalityName': 'Paris',
  'location': {'lat': 48.9694, 'lon': 2.44139},
  'countryCode': 'FR'},
 {'icao': 'KPHT',
  'iata': 'PHT',
  'name': 'Paris Henry County',
  'shortName': 'Henry County',
  'municipalityName': 'Paris',
  'location': {'lat': 36.3382, 'lon': -88.3829},
  'countryCode': 'US'}]

In [12]:
pd.json_normalize(result['items'])

,icao,iata,name,shortName,municipalityName,countryCode,location.lat,location.lon
0,LFPG,CDG,Paris Charles de Gaulle,Charles de Gaulle,Paris,FR,49.0128,2.549999
1,LFPO,ORY,Paris -Orly,-Orly,Paris,FR,48.7253,2.359440
2,LFAT,LTQ,Le Touquet-Paris-Plage Le Touquet-Côte d'Opale,Le Touquet-Côte d'Opale,Le Touquet-Paris-Plage,FR,50.5174,1.620589
3,LFOB,BVA,Beauvais/Tillé Paris Beauvais Tillé,Paris Beauvais Tillé,Beauvais/Tillé,FR,49.4544,2.112780
4,LFPB,LBG,Paris -Le Bourget,-Le Bourget,Paris,FR,48.9694,2.441390
5,KPHT,PHT,Paris Henry County,Henry County,Paris,US,36.3382,-88.382900

In [18]:
icao_from = 'LFPG'
icao_to = 'MRFL'

url = f"https://aerodatabox.p.rapidapi.com/airports/icao/{icao_from}/distance-time/{icao_to}"

response = requests.get(url, headers=headers)

result = response.json()

result

{'from': {'icao': 'LFPG',
  'iata': 'CDG',
  'name': 'Paris Charles de Gaulle',
  'shortName': 'Charles de Gaulle',
  'municipalityName': 'Paris',
  'location': {'lat': 49.0128, 'lon': 2.549999},
  'countryCode': 'FR'},
 'to': {'icao': 'MRFL',
  'iata': 'FMG',
  'name': 'Brasilito Flamingo',
  'shortName': 'Flamingo',
  'municipalityName': 'Brasilito',
  'location': {'lat': 10.4186, 'lon': -85.7827},
  'countryCode': 'CR'},
 'greatCircleDistance': {'meter': 9021517.42,
  'km': 9021.52,
  'mile': 5605.71,
  'nm': 4871.23,
  'feet': 29598154.26},
 'approxFlightTime': '11:05:00'}

In [20]:
pd.json_normalize(result).T

                                                 0
approxFlightTime                          11:05:00
from.icao                                     LFPG
from.iata                                      CDG
from.name                  Paris Charles de Gaulle
from.shortName                   Charles de Gaulle
from.municipalityName                        Paris
from.location.lat                          49.0128
from.location.lon                         2.549999
from.countryCode                                FR
to.icao                                       MRFL
to.iata                                        FMG
to.name                         Brasilito Flamingo
to.shortName                              Flamingo
to.municipalityName                      Brasilito
to.location.lat                            10.4186
to.location.lon                           -85.7827
to.countryCode                                  CR
greatCircleDistance.meter               9021517.42
greatCircleDistance.km                     9021.52
greatCircleDistance.mile                   5605.71
greatCircleDistance.nm                     4871.23
greatCircleDistance.feet               29598154.26

In [27]:
import requests

url = "https://aerodatabox.p.rapidapi.com/flights/airports/iata/LGA/2023-04-04T20:00/2023-04-05T08:00"

querystring = {"withLeg":"true","withCancelled":"true","withCodeshared":"true","withCargo":"true","withPrivate":"true","withLocation":"false"}

headers = {
	"X-RapidAPI-Key": "9613ca6ca5msh62659872159916fp1a0a2cjsndd9a3e6ff324",
	"X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

result = response.json()

In [33]:
result = result['departures'][0]

In [34]:
pd.json_normalize(result).T

                                                    0
number                                         DL 892
callSign                                       DAL892
status                                       Departed
codeshareStatus                            IsOperator
isCargo                                         False
departure.scheduledTimeLocal   2023-04-04 19:35-04:00
departure.actualTimeLocal      2023-04-04 20:02-04:00
departure.runwayTimeLocal      2023-04-04 20:02-04:00
departure.scheduledTimeUtc          2023-04-04 23:35Z
departure.actualTimeUtc             2023-04-05 00:02Z
departure.runwayTimeUtc             2023-04-05 00:02Z
departure.scheduledTime.utc         2023-04-04 23:35Z
departure.scheduledTime.local  2023-04-04 19:35-04:00
departure.revisedTime.utc           2023-04-05 00:02Z
departure.revisedTime.local    2023-04-04 20:02-04:00
departure.runwayTime.utc            2023-04-05 00:02Z
departure.runwayTime.local     2023-04-04 20:02-04:00
departure.terminal                                  C
departure.quality                       [Basic, Live]
arrival.airport.icao                             KPBI
arrival.airport.iata                              PBI
arrival.airport.name                  West Palm Beach
arrival.scheduledTimeLocal     2023-04-04 22:36-04:00
arrival.actualTimeLocal        2023-04-04 22:10-04:00
arrival.runwayTimeLocal        2023-04-04 22:10-04:00
arrival.scheduledTimeUtc            2023-04-05 02:36Z
arrival.actualTimeUtc               2023-04-05 02:10Z
arrival.runwayTimeUtc               2023-04-05 02:10Z
arrival.scheduledTime.utc           2023-04-05 02:36Z
arrival.scheduledTime.local    2023-04-04 22:36-04:00
arrival.revisedTime.utc             2023-04-05 02:10Z
arrival.revisedTime.local      2023-04-04 22:10-04:00
arrival.runwayTime.utc              2023-04-05 02:10Z
arrival.runwayTime.local       2023-04-04 22:10-04:00
arrival.quality                         [Basic, Live]
aircraft.reg                                   N3762Y
aircraft.modeS                                 A44CCA
aircraft.model                         Boeing 737-800
airline.name                          Delta Air Lines
airline.iata                                       DL
airline.icao                                      DAL

In [35]:
# headers won't change
headers = {
    'x-rapidapi-host': "aerodatabox.p.rapidapi.com",
    'x-rapidapi-key': "9613ca6ca5msh62659872159916fp1a0a2cjsndd9a3e6ff324"
    }


def get_codes():

    location = input('Insert location:')
    print()

    url = "https://aerodatabox.p.rapidapi.com/airports/search/term"
    querystring = {"q":location.lower(), "limit":"10"}

    response = requests.get(url, headers=headers, params=querystring)
    codes = response.json()['items'] if 'items' in response.json() else location

    return codes


def choose_code():

    codes = get_codes()

    while type(codes) is str or len(set([code['shortName'] for code in codes])) != 1:

        if not codes:
            print('Try another location. Unable to find code for:', codes, '\n')
        else:
            print('More than one location found. Insert one of the following airports:', [code['shortName'] for code in codes], '\n')

        codes = get_codes()

    return codes[0]['icao']


def flight_distance_time(from_, to_):
    url = f"https://aerodatabox.p.rapidapi.com/airports/icao/{from_}/distance-time/{to_}"
    response = requests.get(url, headers=headers)
    return pd.json_normalize(response.json()).T

In [37]:
print('[DEPARTURE]')
from_ = choose_code()
print('[DESTINATION]')
to_ = choose_code()

flight_df = flight_distance_time(from_, to_)
flight_df

[DEPARTURE]
Insert location:london

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:london

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:London

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:London

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:'London'

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:london

More than one location found. Insert one of the following airports: ['London', 'Luton', 'Gatwick', 'City', 'Heathrow', 'Stansted', 'Biggin Hill', 'RAF Northolt', 'Ben Schoeman', 'Groton New London']

Insert location:gatwick

[DESTINATION]
Insert location:paris

More than one location found. Insert one of the following airports: ['Charles de Gaulle', '-Orly', "Le Touquet-Côte d'Opale", 'Paris Beauvais Tillé', '-Le Bourget', 'Henry County']

Insert location:Charles de Gaulle

                                                 0
approxFlightTime                          00:35:00
from.icao                                     EGKK
from.iata                                      LGW
from.name                           London Gatwick
from.shortName                             Gatwick
from.municipalityName                       London
from.location.lat                          51.1481
from.location.lon                        -0.190277
from.countryCode                                GB
to.icao                                       LFPG
to.iata                                        CDG
to.name                    Paris Charles de Gaulle
to.shortName                     Charles de Gaulle
to.municipalityName                          Paris
to.location.lat                            49.0128
to.location.lon                           2.549999
to.countryCode                                  FR
greatCircleDistance.meter                307983.37
greatCircleDistance.km                      307.98
greatCircleDistance.mile                    191.37
greatCircleDistance.nm                       166.3
greatCircleDistance.feet                1010444.12